### ISSUE TITLE
Will not work in combination with touchend or touchcancel

### ISSUE THREAD

**Issue by julmot** [ssorallen/jquery-scrollstop#7]
when I listen to the scrollstop-event on "touchcancel" or "touchend" the scrollstop-event is not getting fired, but it should since the scroll is stopping when these events are fired after a scroll.

**Comment by ssorallen** [comment]
Can you explain this and give an example?

**Comment by julmot** [comment]
Yes. Almost two years ago...

**Comment by ssorallen** [comment]
Yeah I realized that before commenting! It's been a while. 😬
